### ISSUE TITLE
Visual representation of strand at SV breakpoints

### ISSUE THREAD

**Issue by dominikglodzikhms** [sehilyi/goscan#78]
For interpretation of more complex events, it would be helpful to picture which pieces of DNA are connected as a result of structural variants.

If the grey line denotes a breakpoint, then strands could be represented as horizontal arrows (or segments)
![Screen Shot 2023-01-02 at 10 01 21 PM](https://user-images.githubusercontent.com/82227017/210295055-bfb34b29-4b9b-41f0-9a00-d4281c8de1cb.png)

Many thanks!

**Comment by sehilyi** [comment]
Support for all SV types
