### ISSUE TITLE
Driver file formats

### ISSUE THREAD

**Issue by dominikglodzikhms** [sehilyi/goscan#89]
The required format of driver files is described here:
https://sehilyi.github.io/goscan/docs/#/data-formats?id=drivers-tsv

I wonder if we could explore alternatives to this format. Would parsing a .json file be possible instead?

**Comment by sehilyi** [comment]
Addressed by [a24dd36](https://github.com/sehilyi/goscan/commit/a24dd361ab1c40b520c8358ede68f316821113ab)
